export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";

// Project Creation

export const GET_USERS_PROJECT = "GET_USERS_PROJECT";
export const USERS_PROJECT_ERROR = "USERS_PROJECT_ERROR";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";
export const CHAPTER_PROJECT = "CHAPTER_PROJECT";
export const CHAPTER_PROJECT_ERROR = "CHAPTER_PROJECT_ERROR";
export const TYPE_PROJECT = "TYPE_PROJECT";
export const TYPE_PROJECT_ERROR = "TYPE_PROJECT_ERROR";
export const CREATE_CHAPTER_TYPE = "CREATE_CHAPTER_TYPE";
export const CREATE_CHAPTER_TYPE_ERROR = "CREATE_CHAPTER_ERROR";
export const UPDATE_CHAPTER_TYPE = "CREATE_CHAPTER_TYPE";
export const UPDATE_CHAPTER_TYPE_ERROR = "CREATE_CHAPTER_ERROR";
export const GET_CHAPTER_DATA = "GET_CHAPTER_DATA";
export const GET_CHAPTER_DATA_ERROR = "GET_CHAPTER_DATA_ERROR";

//----------------------------------------------------------------

// Chapter 3 FLow

export const GET_CHAPTER_3_DATA = "GET_CHAPTER_3_DATA";
export const GET_CHAPTER_3_DATA_ERROR = "GET_CHAPTER_3_DATA_ERROR";
export const CREATE_QUESTIONS = "CREATE_QUESTIONS";
export const CREATE_QUESTIONS_ERROR = "CREATE_QUESTIONS_ERROR";
export const GET_PREVOIUS_DATA = "GET_PREVOIUS_DATA";
export const GET_PREVOIUS_DATA_ERROR = "GET_PREVOIUS_DATA_ERROR";
export const GET_CHAPTER_TWO_DATA = "GET_CHAPTER_TWO_DATA";
export const GET_CHAPTER_TWO_ANSWER_DATA = "GET_CHAPTER_TWO_ANSWER_DATA";
export const CREATE_CHAPTER_TWO = "CREATE_CHAPTER_TWO";
export const CREATE_CHAPTER_FIVE = "CREATE_CHAPTER_FIVE";
export const GET_CHAPTER_TWO_DATA_ANSWER = "GET_CHAPTER_TWO_DATA_ANSWER";
export const GET_CHAPTER_FIVE_REPORT_DATA = "GET_CHAPTER_FIVE_REPORT_DATA";
export const GET_CHAPTER_FIVE_QUESTION = "GET_CHAPTER_FIVE_QUESTION";
export const GET_PROJECT_STATUS = "GET_PROJECT_STATUS";
export const GET_COMMON_REPORT_DATA = "GET_COMMON_REPORT_DATA";
export const GET_REPORT_DATA = "GET_REPORT_DATA";
export const GET_REPORT_DATA_ERROR = "GET_REPORT_DATA_ERROR";
export const CREATE_CHAPTER_4_STATUS = "CREATE_CHAPTER_4_STATUS";
